const { createClient } = require('@supabase/supabase-js');
const fs = require('fs');
const path = require('path');

require('dotenv').config({ path: path.join(__dirname, '.env') });

const supabase = createClient(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_SERVICE_ROLE_KEY
);

const SQL_SEED = `
-- SPICES
INSERT INTO spices (name, slug, tagline, origin_story, culinary_uses, ayurvedic_benefits, growing_season, dish_it_transforms, flavor_profile, image_url) VALUES
('Cardamom', 'cardamom', 'The Queen of Spices', 'Cardamom has been cultivated for over 4,000 years in the Western Ghats of India. Known to ancient Egyptians, cardamom traveled the spice routes of Arabia before becoming a prized ingredient in Ayurvedic medicine and Mughal cuisine.', 'Cardamom is used in biryanis, chai masala, desserts like kheer and gulab jamun, and Scandinavian pastries. The pods lend a floral warmth to curries and are the secret ingredient in Hyderabadi haleem.', 'Cardamom aids digestion, freshens breath, acts as a natural antioxidant, and is used to treat nausea. In Ayurveda it is classified as tridoshic and is used to balance all three doshas.', 'Harvested in August through November when pods are plump but still green.', 'Masala Chai', '{"warmth": 7, "sweetness": 6, "floral": 9, "spice": 5, "aroma": 10}', 'https://images.unsplash.com/photo-1632396870809-bcb65da5f0d9?w=600'),
('Black Pepper', 'black-pepper', 'The King of Spices', 'Black pepper has been a prized commodity for over 3,000 years, once used as currency in ancient trade. Native to Kerala, it was the backbone of the spice trade that brought Vasco da Gama to India in 1498.', 'Black pepper is the world''s most traded spice. It elevates everything from rasam and chettinad curry to steak au poivre. Freshly cracked pepper transforms scrambled eggs and pasta alike.', 'Black pepper stimulates digestive enzymes, enhances bioavailability of curcumin in turmeric, has anti-inflammatory properties, and is used in Ayurveda to treat respiratory conditions.', 'Pepper berries are harvested green in January through April, sun-dried to black.', 'Rasam', '{"heat": 8, "pungency": 9, "earthiness": 7, "aroma": 8, "sharpness": 9}', 'https://images.unsplash.com/photo-1588167056547-c3fd72d7a0e5?w=600'),
('Turmeric', 'turmeric', 'The Golden Healer', 'Turmeric has been cultivated in India for over 4,000 years. Ancient Sanskrit texts mention it as a treatment for liver disorders and poor digestion. Known as Haridra in Ayurveda, it is considered sacred and auspicious.', 'Turmeric colors curries, dal, and rice dishes golden yellow. It is used in golden milk, pickle brines, and as a natural food coloring. Fresh turmeric rhizomes are used in Thai and Indonesian cuisines.', 'Curcumin in turmeric is a powerful anti-inflammatory and antioxidant. Used in Ayurveda for wound healing, joint pain, digestive disorders, and immunity. The bioavailability of curcumin increases significantly when combined with black pepper.', 'Rhizomes are harvested in December through January, 7-10 months after planting.', 'Dal Tadka', '{"earthiness": 8, "bitterness": 5, "warmth": 7, "pungency": 4, "aroma": 6}', 'https://images.unsplash.com/photo-1615485290382-441e4d049cb5?w=600'),
('Cinnamon', 'cinnamon', 'The Sweet Bark of Antiquity', 'True cinnamon (Cinnamomum verum) is native to Sri Lanka. It was so valuable in ancient times that it was worth more than gold by weight. Arab traders concealed its source for centuries to maintain their monopoly.', 'Cinnamon is used in biryani, curries, mulled wine, apple pie, French toast, and Mexican mole sauce. The quills release fragrant warmth that defines winter spice blends worldwide.', 'Cinnamon regulates blood sugar levels, has antimicrobial properties, supports heart health, and reduces inflammation. Cinnamon oil has been used traditionally to treat infections and digestive issues.', 'Bark is harvested twice a year during the monsoon when peeling is easiest, from 2-year-old branches.', 'Biryani', '{"sweetness": 8, "warmth": 7, "woodiness": 6, "spice": 4, "aroma": 9}', 'https://images.unsplash.com/photo-1599233245135-b97ec75f03a1?w=600'),
('Cloves', 'cloves', 'The Nail of Zanzibar', 'Cloves are the dried flower buds of a tree native to the Maluku Islands Indonesia. Their trade was so valuable that in the 17th century, the Dutch East India Company controlled clove production violently to maintain a monopoly.', 'Cloves are used in garam masala, mulled cider, holiday cookies, biryani, and Worcestershire sauce. They are also used to stud oranges for pomanders and flavor ham glazes.', 'Cloves have the highest antioxidant content of any spice. Eugenol, their primary compound, has analgesic and antibacterial properties. Used in dental care to numb toothache and kill oral bacteria.', 'Buds are hand-picked before they bloom, from July through September.', 'Biryani Garam Masala', '{"intensity": 10, "sweetness": 5, "warmth": 9, "pungency": 7, "aroma": 10}', 'https://images.unsplash.com/photo-1615485500704-8e3b5b8b7865?w=600'),
('Ginger', 'ginger', 'The Universal Medicine', 'Ginger originated in Maritime Southeast Asia and was one of the first spices exported to Europe. Confucius ate ginger with every meal. In Ayurveda, it is called Vishvabhesaj — the universal medicine.', 'Ginger is used fresh, dried, pickled, and candied. It anchors Southeast Asian stir-fries, Japanese sushi, Indian chai, and Jamaican ginger beer. Ginger juice brightens marinades and salad dressings.', 'Ginger is one of the most scientifically studied natural remedies. It reduces nausea, relieves muscle pain, has anti-inflammatory properties equal to ibuprofen, and supports immune function.', 'Rhizomes are harvested 8-10 months after planting in November through January.', 'Chai Masala', '{"heat": 7, "freshness": 8, "pungency": 6, "sweetness": 3, "aroma": 8}', 'https://images.unsplash.com/photo-1589927986089-35812388d1f4?w=600'),
('Nutmeg', 'nutmeg', 'The Spice Island Treasure', 'Nutmeg is native to the Banda Islands of Indonesia. In the 17th century, it was literally worth its weight in gold in Europe. The Dutch traded Manhattan (then Nieuw Amsterdam) for Run Island — a nutmeg island.', 'Nutmeg is indispensable in béchamel sauce, eggnog, pumpkin pie, and Indian korma. The outer covering — mace — is a separate spice used in lighter preparations and pickles.', 'Nutmeg has antibacterial, anti-inflammatory, and sedative properties. In Ayurveda it is used to treat insomnia, digestive disorders, and pain. Used in small quantities — large amounts are toxic.', 'Pods are harvested when the fruit splits naturally, revealing the crimson mace surrounding the nut.', 'Mughal Korma', '{"warmth": 8, "sweetness": 7, "woodiness": 6, "spice": 5, "aroma": 9}', 'https://images.unsplash.com/photo-1599788824752-d7fc7bec1e3c?w=600'),
('Chili', 'chili', 'The Fire from the Americas', 'Chili peppers originated in Mexico and were brought to India by Portuguese traders in the 16th century. Within a century, they completely replaced black pepper as India''s primary heat source and became central to Indian cuisine.', 'Chili transforms Indian curries, Mexican salsas, Thai soups, and Korean kimchi. Dried chilis add depth and color to tadkas. The Kashmiri chili variety is prized for its brilliant red color and mild heat.', 'Capsaicin in chili peppers triggers endorphin release creating a euphoric sensation. Used medicinally for pain relief, as a metabolism booster, and anti-inflammatory. Rich in Vitamin C and antioxidants.', 'Harvested June through October when fruits turn from green to full red maturity.', 'Hyderabadi Biryani', '{"heat": 10, "fruitiness": 6, "earthiness": 5, "sweetness": 3, "color": 9}', 'https://images.unsplash.com/photo-1526318472351-c75fcf070305?w=600'),
('Vanilla', 'vanilla', 'The Orchid of Spices', 'Vanilla is the only edible fruit of the orchid family, native to Mexico. The Totonac people of Mexico were the first to cultivate it. Each vanilla flower blooms for just one day and must be hand-pollinated.', 'Vanilla is used in ice cream, custards, cakes, chocolate, and perfumes. Mexican vanilla has a creamy woodiness while Tahitian vanilla is more floral. Pure vanilla extract transforms simple desserts into extraordinary ones.', 'Vanillin in vanilla has antioxidant and anti-inflammatory properties. Studies suggest vanilla essential oil reduces anxiety and has mild sedative effects. Used in aromatherapy for calming.', 'Hand-pollinated flowers develop into pods over 9 months. Pods are harvested green, then cured for 3-6 months.', 'Crème Brûlée', '{"sweetness": 10, "floral": 8, "warmth": 5, "creaminess": 9, "aroma": 10}', 'https://images.unsplash.com/photo-1595854341625-f33ee10dbf9f?w=600'),
('Lemongrass', 'lemongrass', 'The Citrus Blade of Asia', 'Lemongrass is native to tropical South Asia and Southeast Asia. In India, it has been used in Ayurvedic medicine for centuries as a digestive aid and fever reducer. Its refreshing citrus aroma made it a staple of temple rituals.', 'Lemongrass stalks flavor Thai curries, Vietnamese pho, and Indonesian satay. The inner stalk is pounded into Thai green curry paste. Dried lemongrass makes refreshing herbal teas popular across Asia.', 'Lemongrass has antimicrobial, anti-inflammatory, and antifungal properties. It relieves digestive disorders, reduces anxiety, and is used in detox teas. Citral compounds inhibit fungal and bacterial growth.', 'Continuously harvested year-round in tropical climates — cut and regrows from the base.', 'Tom Kha Gai', '{"freshness": 10, "citrus": 9, "floral": 6, "herbal": 8, "aroma": 9}', 'https://images.unsplash.com/photo-1558346490-a72e53ae2d4f?w=600'),
('Curry Leaf', 'curry-leaf', 'The Aromatic Soul of South India', 'Curry leaves are native to South Asia, mentioned in ancient Tamil literature dating to 1st century CE. Called Murraya koenigii, they have been integral to South Indian cooking for over 2,000 years and hold a central place in Ayurvedic medicine.', 'Fresh curry leaves are tempered in hot oil releasing their unique nutty, citrusy fragrance. Used in dal tadka, sambar, rasam, kadhi, chutneys, and as a garnish for biryani. Dried leaves have far less potency.', 'Curry leaves are rich in iron, calcium, and Vitamin A. In Ayurveda, used to promote hair growth, prevent greying, manage blood sugar levels, and as an antioxidant-rich digestive tonic.', 'Harvested year-round but most aromatic during flowering periods in summer.', 'South Indian Tadka Dal', '{"aromatic": 10, "nutty": 7, "citrus": 6, "bitterness": 4, "freshness": 8}', 'https://images.unsplash.com/photo-1585095595205-e8f584e1ab22?w=600'),
('Star Anise', 'star-anise', 'The Eight-Pointed Star of Chinese Medicine', 'Star anise is native to the limestone hills of Yunnan province, China. It has been used in Chinese cuisine and traditional medicine for over 3,000 years. Its primary compound, shikimic acid, is used to make Tamiflu (oseltamivir) for influenza treatment.', 'Star anise is a cornerstone of Chinese five-spice powder and Vietnamese pho broth. It flavors mulled wine, Indian biryani, lentil dishes, and licorice-flavored sweets. A little goes an extraordinarily long way.', 'Star anise is a powerful antibacterial, antifungal, and antiviral agent. Rich in antioxidants including anethole, linalool, and vitamin C. Provides significant relief for digestive issues and cough.', 'Harvested twice a year from the evergreen trees — spring and autumn harvests.', 'Pho Bo', '{"anise": 10, "sweetness": 6, "warmth": 7, "intensity": 8, "aroma": 10}', 'https://images.unsplash.com/photo-1599588815453-0a8a32e87e74?w=600')
ON CONFLICT (slug) DO NOTHING;

-- TESTIMONIALS
INSERT INTO testimonials (visitor_name, city, rating, review, visit_date, approved) VALUES
('Priya Sharma', 'Hyderabad', 5, 'Absolutely magical! The aroma of fresh cardamom and black pepper as you walk through the garden is unlike anything I''ve experienced. The guide was incredibly knowledgeable about Ayurvedic uses of each spice. My children were completely engaged. This is Hyderabad''s secret green gem.', '2024-11-12', true),
('Ravi Kumar', 'Bengaluru', 5, 'We made a road trip from Bengaluru just for this. Completely worth it. The guided tour was fascinating — learning how pepper was once traded for gold, and seeing vanilla orchids in person changed how I see my spice rack. A truly enriching botanical experience.', '2024-10-05', true),
('Dr. Meena Patel', 'Mumbai', 5, 'As an Ayurvedic practitioner, I was blown away by the depth of botanical knowledge the guides possess. Every plant is presented with its Ayurvedic properties and historical context. I''ve been recommending it to all my patients as a wellness experience.', '2024-09-20', true),
('Arjun Mehta', 'Hyderabad', 4, 'The photography zone is spectacular during golden hour. Got some of my best macro shots here — pepper vines with dew drops, cardamom pods against green light, ginger rhizomes in soil. The team allowed me to take my time. Will definitely come back with a better camera setup.', '2024-11-28', true),
('Lakshmi Venkat', 'Chennai', 5, 'Our school group of 45 students had an absolutely incredible time. The educators tailored the tour beautifully to our 8th graders. The spice tasting session was the highlight — students who had never cared about science suddenly wanted to know everything about plant chemistry!', '2024-10-18', true),
('Rahul Goel', 'Delhi', 5, 'I thought I knew spices. I was wrong. The star anise session alone taught me three things I''d never read in any cookbook. The tasting menu of fresh vs dried spices was eye-opening. The yoga session at sunrise in the spice garden is something I''ll remember forever.', '2024-12-01', true)
ON CONFLICT DO NOTHING;

-- EVENTS
INSERT INTO events (title, description, event_date, event_type, active) VALUES
('Ugadi Spice Harvest Festival', 'Join us for our annual Ugadi celebration featuring a traditional spice harvest ritual, fresh-picked cardamom tastings, guided Ayurvedic medicine tours, and a Hyderabadi spice biryani lunch prepared by our resident chef.', '2026-03-30 08:00:00+05:30', 'Festival', true),
('Yoga in the Spice Garden — Spring Sessions', 'Morning yoga and pranayama surrounded by aromatic lemongrass and cardamom plants. Sessions led by certified yoga instructor with 15 years of experience. Limited to 20 participants for an intimate experience.', '2026-03-07 06:30:00+05:30', 'Wellness', true),
('Botanical Photography Masterclass', 'Join award-winning nature photographer Rakesh Rao for a hands-on masterclass in botanical macro photography. Learn composition, natural lighting techniques, and how to capture the texture and color of spice plants.', '2026-04-12 16:30:00+05:30', 'Workshop', true),
('Spice & Ayurveda Weekend Workshop', 'An immersive two-day program exploring the intersection of culinary spices and Ayurvedic medicine. Learn to make your own churnas (herbal powders), spice-infused oils, and Ayurvedic teas.', '2026-04-19 09:00:00+05:30', 'Workshop', true)
ON CONFLICT DO NOTHING;

-- BLOG POSTS
INSERT INTO blog_posts (title, slug, excerpt, content, category, author, published, published_at, featured_image_url) VALUES
('The Secret Life of Cardamom Pods', 'secret-life-of-cardamom', 'Cardamom is the world''s third most expensive spice by weight, and understanding its harvest cycle reveals why.', 'Walking through the cardamom section of Spice Garden at sunrise, when the pods are heavy with morning dew and the air carries their extraordinary fragrance, you understand immediately why this spice was once worth three times its weight in silver.\n\nCardamom (Elettaria cardamomum) grows as a perennial herb in tropical forests, reaching up to 5 meters tall. Each plant produces elongated pods through basal shoots — meaning the pods grow right from the base of the plant, close to the ground, rather than on the leaves or stalks.\n\nThe harvesting process is entirely manual and requires remarkable skill. Pickers must identify pods at the exact moment of perfect ripeness — still green, plump, and firm — selecting individual pods while leaving under-ripe ones to mature. A single skilled harvester can process only 10-15 kg of fresh pods per day.\n\nAt Spice Garden, we grow three varieties: Alleppey Green (the most prized), Coorg Green, and Mysore. Each has a subtly different flavor profile — Alleppey being more intensely aromatic, Coorg more balanced, and Mysore slightly sweeter.\n\nThe pods are then carefully dried, reducing their moisture from 80% to below 12%. The key is retaining the volatile oils — linalool, linalyl acetate, and cineol — that give cardamom its distinctive flavor. Too much heat and these oils evaporate. Too little and the pods develop mold.\n\nNext time you add cardamom to your chai or biryani, you''re using a spice that traveled from Kerala to the ancient world through Arabian traders, appeared in ancient Egyptian tombs, and was used as currency in medieval Europe. That''s a remarkable story packed into each tiny pod.', 'Spice Stories', 'Spice Garden Team', true, '2024-11-15 09:00:00+05:30', 'https://images.unsplash.com/photo-1632396870809-bcb65da5f0d9?w=800'),
('Why Turmeric Works Best with Black Pepper', 'turmeric-and-black-pepper', 'Ancient Ayurvedic wisdom is being confirmed by modern molecular science — the reason Indians always combined these two spices is biological.', 'For thousands of years, Indian cooking and Ayurvedic medicine combined turmeric and black pepper almost instinctively. The Charaka Samhita — a foundational Ayurvedic text written around 500 BCE — prescribed the combination for treating inflammation and digestive disorders.\n\nModern molecular science now tells us exactly why this combination works so powerfully.\n\nTurmeric''s active compound, curcumin, is a remarkable molecule with potent anti-inflammatory and antioxidant properties. But it has one critical weakness: incredibly poor bioavailability. When you consume curcumin alone, your liver and intestinal wall metabolize and excrete it so rapidly that almost none reaches your bloodstream.\n\nBlack pepper''s piperine changes everything. Piperine inhibits the metabolic enzymes that break down curcumin, dramatically slowing its elimination. Studies show that piperine increases curcumin bioavailability by 2,000% — that''s not a typo, two thousand percent.\n\nThis is why the Ayurvedic formulation haldi doodh (golden milk) has always included black pepper — long before anyone understood the underlying molecular mechanism. The ancients observed the effect empirically over generations and codified it into their healing traditions.\n\nAt Spice Garden, we grow both in adjoining sections so visitors can experience this fascinating botanical partnership. Our guides often demonstrate the synergy with a simple tea preparation.\n\nThe next time you make a turmeric-based dish, remember: a small pinch of black pepper isn''t just about flavor — it''s about activating one of nature''s most potent healing compounds.', 'Ayurveda', 'Dr. Ananya Krishnamurthy', true, '2024-10-28 09:00:00+05:30', 'https://images.unsplash.com/photo-1615485290382-441e4d049cb5?w=800'),
('Hyderabad Through the Spice Route', 'hyderabad-spice-route-history', 'The story of Hyderabad is inseparable from the history of spices. How the Nizam''s city became a culinary capital.', 'Hyderabad''s culinary identity — the biryani, the haleem, the rich Mughal-influenced gravies — cannot be understood without understanding the spice trade routes that shaped the city.\n\nThe city was founded in 1591 by Muhammad Quli Qutb Shah, and from its earliest days was positioned as a crossroads between the northern Mughal empire and the spice-producing south. Caravans carrying cardamom from Kerala, black pepper from Kerala''s Malabar coast, and saffron from Kashmir converged here.\n\nThe Hyderabadi kitchen that emerged from this convergence was extraordinary — taking the Mughal tradition of Persian-influenced slow-cooked biryanis and enriching them with the aromatic intensity of southern spices. The hallmark of Hyderabadi cooking is the precise architectural layering of spice aromatics: aromatics first (cardamom, cinnamon, cloves), then base spices (turmeric, chili), then finishing spices (garam masala, fresh herb).', 'History', 'Spice Garden Team', true, '2024-12-05 09:00:00+05:30', 'https://images.unsplash.com/photo-1564671165093-20688ff1fffa?w=800')
ON CONFLICT (slug) DO NOTHING;

-- GALLERY IMAGES
INSERT INTO gallery_images (image_url, caption, category, sort_order, active) VALUES
('https://images.unsplash.com/photo-1596040033229-a9821ebd058d?w=800', 'Morning light through cardamom plants', 'Spices', 1, true),
('https://images.unsplash.com/photo-1588167056547-c3fd72d7a0e5?w=800', 'Black pepper vines in full season', 'Spices', 2, true),
('https://images.unsplash.com/photo-1615485290382-441e4d049cb5?w=800', 'Fresh turmeric rhizomes at harvest', 'Spices', 3, true),
('https://images.unsplash.com/photo-1441974231531-c6227db76b6e?w=800', 'Nature walk through the botanical trails', 'Visitors', 4, true),
('https://images.unsplash.com/photo-1506126613408-eca07ce68773?w=800', 'Sunrise yoga in the spice garden', 'Events', 5, true),
('https://images.unsplash.com/photo-1589927986089-35812388d1f4?w=800', 'Ginger rhizomes ready for harvest', 'Spices', 6, true),
('https://images.unsplash.com/photo-1471684644823-6f74e5e4e2e6?w=800', 'Photography in the botanical zone', 'Visitors', 7, true),
('https://images.unsplash.com/photo-1558346490-a72e53ae2d4f?w=800', 'Lemongrass grove in evening light', 'Spices', 8, true),
('https://images.unsplash.com/photo-1632396870809-bcb65da5f0d9?w=800', 'Cardamom pods close-up macro', 'Spices', 9, true),
('https://images.unsplash.com/photo-1500534314209-a25ddb2bd429?w=800', 'Guided tour group through garden paths', 'Visitors', 10, true),
('https://images.unsplash.com/photo-1564671165093-20688ff1fffa?w=800', 'Evening view of Indira Park surroundings', 'Aerial', 11, true),
('https://images.unsplash.com/photo-1526318472351-c75fcf070305?w=800', 'Chili plants in full bloom', 'Spices', 12, true)
ON CONFLICT DO NOTHING;
`;

async function runSeed() {
    console.log('Running Supabase schema migration...');

    const schemaSql = fs.readFileSync(path.join(__dirname, 'supabase/migrations/20240101000000_init.sql'), 'utf8');

    // Run schema
    const { error: schemaError } = await supabase.rpc('exec_sql', { sql: schemaSql }).catch(() => ({ error: null }));
    if (schemaError) {
        console.log('Schema via RPC failed, tables may already exist. Continuing...');
    }

    // Run seed
    const statements = SQL_SEED.split(');').filter(s => s.trim().length > 4);
    let success = 0, failed = 0;

    for (const stmt of statements) {
        const sql = stmt.trim() + (stmt.trim().endsWith(')') ? '' : ')') + ';';
        if (sql.length < 10) continue;
        const { error } = await supabase.rpc('exec_sql', { sql }).catch(() => ({ error: 'rpc failed' }));
        if (error) { failed++; } else { success++; }
    }

    console.log(`Done! ${success} succeeded, ${failed} failed (may use direct insert instead).`);

    // Try direct inserts as fallback
    console.log('Trying direct inserts fallback...');

    const { error: spiceErr } = await supabase.from('spices').insert([
        { name: 'Cardamom', slug: 'cardamom', tagline: 'The Queen of Spices', origin_story: 'Cardamom has been cultivated for over 4,000 years in the Western Ghats of India. Known to ancient Egyptians, cardamom traveled the spice routes of Arabia before becoming a prized ingredient in Ayurvedic medicine and Mughal cuisine.', culinary_uses: 'Used in biryanis, chai masala, desserts like kheer and gulab jamun, and Scandinavian pastries.', ayurvedic_benefits: 'Cardamom aids digestion, freshens breath, acts as a natural antioxidant, and is used to treat nausea.', growing_season: 'Harvested August–November when pods are plump but still green.', dish_it_transforms: 'Masala Chai', flavor_profile: { warmth: 7, sweetness: 6, floral: 9, spice: 5, aroma: 10 }, image_url: 'https://images.unsplash.com/photo-1632396870809-bcb65da5f0d9?w=600' },
        { name: 'Black Pepper', slug: 'black-pepper', tagline: 'The King of Spices', origin_story: 'Black pepper has been a prized commodity for over 3,000 years, once used as currency in ancient trade. Native to Kerala, it was the backbone of the spice trade that brought Vasco da Gama to India in 1498.', culinary_uses: 'Black pepper is the world\'s most traded spice. It elevates everything from rasam and chettinad curry to steak au poivre.', ayurvedic_benefits: 'Stimulates digestive enzymes, enhances bioavailability of curcumin in turmeric, has anti-inflammatory properties.', growing_season: 'Pepper berries are harvested green in January–April, sun-dried to black.', dish_it_transforms: 'Rasam', flavor_profile: { heat: 8, pungency: 9, earthiness: 7, aroma: 8, sharpness: 9 }, image_url: 'https://images.unsplash.com/photo-1588167056547-c3fd72d7a0e5?w=600' },
        { name: 'Turmeric', slug: 'turmeric', tagline: 'The Golden Healer', origin_story: 'Turmeric has been cultivated in India for over 4,000 years. Ancient Sanskrit texts mention it as a treatment for liver disorders. Known as Haridra in Ayurveda, it is considered sacred and auspicious.', culinary_uses: 'Colors curries, dal, and rice dishes golden yellow. Used in golden milk, pickle brines, and as a natural food coloring.', ayurvedic_benefits: 'Curcumin is a powerful anti-inflammatory and antioxidant. Used for wound healing, joint pain, digestive disorders, and immunity.', growing_season: 'Rhizomes harvested December–January, 7–10 months after planting.', dish_it_transforms: 'Dal Tadka', flavor_profile: { earthiness: 8, bitterness: 5, warmth: 7, pungency: 4, aroma: 6 }, image_url: 'https://images.unsplash.com/photo-1615485290382-441e4d049cb5?w=600' },
        { name: 'Cinnamon', slug: 'cinnamon', tagline: 'The Sweet Bark of Antiquity', origin_story: 'True cinnamon (Cinnamomum verum) is native to Sri Lanka. It was worth more than gold by weight in ancient times. Arab traders concealed its source for centuries.', culinary_uses: 'Used in biryani, curries, mulled wine, apple pie, French toast, and Mexican mole sauce.', ayurvedic_benefits: 'Regulates blood sugar levels, has antimicrobial properties, supports heart health.', growing_season: 'Bark harvested twice a year during monsoon from 2-year-old branches.', dish_it_transforms: 'Biryani', flavor_profile: { sweetness: 8, warmth: 7, woodiness: 6, spice: 4, aroma: 9 }, image_url: 'https://images.unsplash.com/photo-1599233245135-b97ec75f03a1?w=600' },
        { name: 'Cloves', slug: 'cloves', tagline: 'The Nail of Zanzibar', origin_story: 'Cloves are dried flower buds native to the Maluku Islands, Indonesia. Their trade was so valuable the Dutch East India Company controlled production violently.', culinary_uses: 'Used in garam masala, mulled cider, holiday cookies, biryani, and Worcestershire sauce.', ayurvedic_benefits: 'Highest antioxidant content of any spice. Eugenol has analgesic and antibacterial properties. Used in dental care.', growing_season: 'Buds hand-picked before they bloom, July–September.', dish_it_transforms: 'Biryani Garam Masala', flavor_profile: { intensity: 10, sweetness: 5, warmth: 9, pungency: 7, aroma: 10 }, image_url: 'https://images.unsplash.com/photo-1615485500704-8e3b5b8b7865?w=600' },
        { name: 'Ginger', slug: 'ginger', tagline: 'The Universal Medicine', origin_story: 'Ginger originated in Maritime Southeast Asia and was one of the first spices exported to Europe. Confucius ate ginger with every meal. Called Vishvabhesaj in Ayurveda — the universal medicine.', culinary_uses: 'Used fresh, dried, pickled, and candied. Anchors Southeast Asian stir-fries, Japanese sushi, Indian chai, and Jamaican ginger beer.', ayurvedic_benefits: 'Reduces nausea, relieves muscle pain, has anti-inflammatory properties, supports immune function.', growing_season: 'Rhizomes harvested 8–10 months after planting in November–January.', dish_it_transforms: 'Chai Masala', flavor_profile: { heat: 7, freshness: 8, pungency: 6, sweetness: 3, aroma: 8 }, image_url: 'https://images.unsplash.com/photo-1589927986089-35812388d1f4?w=600' },
        { name: 'Nutmeg', slug: 'nutmeg', tagline: 'The Spice Island Treasure', origin_story: 'Nutmeg is native to the Banda Islands of Indonesia. The Dutch traded Manhattan for a nutmeg island. Worth its weight in gold in 17th century Europe.', culinary_uses: 'Indispensable in béchamel sauce, eggnog, pumpkin pie, and Indian korma. Mace (the outer covering) is a separate spice.', ayurvedic_benefits: 'Antibacterial, anti-inflammatory, and sedative properties. Used to treat insomnia, digestive disorders.', growing_season: 'Pods harvested when the fruit splits naturally, revealing the crimson mace.', dish_it_transforms: 'Mughal Korma', flavor_profile: { warmth: 8, sweetness: 7, woodiness: 6, spice: 5, aroma: 9 }, image_url: 'https://images.unsplash.com/photo-1599788824752-d7fc7bec1e3c?w=600' },
        { name: 'Chili', slug: 'chili', tagline: 'The Fire from the Americas', origin_story: 'Chili peppers originated in Mexico, brought to India by Portuguese traders in the 16th century. Within a century they completely replaced black pepper as India\'s primary heat source.', culinary_uses: 'Transforms Indian curries, Mexican salsas, Thai soups, and Korean kimchi. Kashmiri chili is prized for brilliant red color.', ayurvedic_benefits: 'Capsaicin triggers endorphin release. Used medicinally for pain relief, as a metabolism booster. Rich in Vitamin C.', growing_season: 'Harvested June–October when fruits turn from green to full red maturity.', dish_it_transforms: 'Hyderabadi Biryani', flavor_profile: { heat: 10, fruitiness: 6, earthiness: 5, sweetness: 3, color: 9 }, image_url: 'https://images.unsplash.com/photo-1526318472351-c75fcf070305?w=600' },
        { name: 'Vanilla', slug: 'vanilla', tagline: 'The Orchid of Spices', origin_story: 'Vanilla is the only edible orchid fruit, native to Mexico. The Totonac people were first to cultivate it. Each vanilla flower blooms for just one day and must be hand-pollinated.', culinary_uses: 'Used in ice cream, custards, cakes, and perfumes. Pure vanilla extract transforms simple desserts into extraordinary ones.', ayurvedic_benefits: 'Vanillin has antioxidant and anti-inflammatory properties. Vanilla essential oil reduces anxiety and has mild sedative effects.', growing_season: 'Hand-pollinated flowers develop into pods over 9 months. Cured for 3–6 months after harvest.', dish_it_transforms: 'Crème Brûlée', flavor_profile: { sweetness: 10, floral: 8, warmth: 5, creaminess: 9, aroma: 10 }, image_url: 'https://images.unsplash.com/photo-1595854341625-f33ee10dbf9f?w=600' },
        { name: 'Lemongrass', slug: 'lemongrass', tagline: 'The Citrus Blade of Asia', origin_story: 'Lemongrass is native to tropical South Asia and Southeast Asia. Used in Ayurvedic medicine for centuries as a digestive aid. Its refreshing citrus aroma made it a staple of temple rituals.', culinary_uses: 'Flavors Thai curries, Vietnamese pho, and Indonesian satay. Dried lemongrass makes refreshing herbal teas popular across Asia.', ayurvedic_benefits: 'Antimicrobial, anti-inflammatory, and antifungal properties. Relieves digestive disorders, reduces anxiety.', growing_season: 'Continuously harvested year-round in tropical climates — cut and regrows from the base.', dish_it_transforms: 'Tom Kha Gai', flavor_profile: { freshness: 10, citrus: 9, floral: 6, herbal: 8, aroma: 9 }, image_url: 'https://images.unsplash.com/photo-1558346490-a72e53ae2d4f?w=600' },
        { name: 'Curry Leaf', slug: 'curry-leaf', tagline: 'The Aromatic Soul of South India', origin_story: 'Curry leaves are native to South Asia, mentioned in ancient Tamil literature dating to 1st century CE. Integral to South Indian cooking for over 2,000 years.', culinary_uses: 'Fresh leaves are tempered in hot oil. Used in dal tadka, sambar, rasam, kadhi, chutneys, and as a garnish for biryani.', ayurvedic_benefits: 'Rich in iron, calcium, and Vitamin A. Used to promote hair growth, prevent greying, manage blood sugar levels.', growing_season: 'Harvested year-round but most aromatic during flowering periods in summer.', dish_it_transforms: 'South Indian Tadka Dal', flavor_profile: { aromatic: 10, nutty: 7, citrus: 6, bitterness: 4, freshness: 8 }, image_url: 'https://images.unsplash.com/photo-1585095595205-e8f584e1ab22?w=600' },
        { name: 'Star Anise', slug: 'star-anise', tagline: 'The Eight-Pointed Star of Chinese Medicine', origin_story: 'Star anise is native to the limestone hills of Yunnan province, China. Used in Chinese cuisine for over 3,000 years. Its compound shikimic acid is used to make Tamiflu.', culinary_uses: 'Cornerstone of Chinese five-spice powder and Vietnamese pho broth. Flavors mulled wine, Indian biryani, and licorice-flavored sweets.', ayurvedic_benefits: 'Powerful antibacterial, antifungal, and antiviral agent. Rich in antioxidants including anethole and vitamin C.', growing_season: 'Harvested twice a year from evergreen trees — spring and autumn harvests.', dish_it_transforms: 'Pho Bo', flavor_profile: { anise: 10, sweetness: 6, warmth: 7, intensity: 8, aroma: 10 }, image_url: 'https://images.unsplash.com/photo-1599588815453-0a8a32e87e74?w=600' }
    ]).select();

    if (spiceErr && spiceErr.code !== '23505') {
        console.error('Spice insert error:', spiceErr.message);
    } else {
        console.log('Spices inserted successfully!');
    }

    const { error: testErr } = await supabase.from('testimonials').insert([
        { visitor_name: 'Priya Sharma', city: 'Hyderabad', rating: 5, review: 'Absolutely magical! The aroma of fresh cardamom and black pepper as you walk through the garden is unlike anything I\'ve experienced. The guide was incredibly knowledgeable about Ayurvedic uses of each spice.', visit_date: '2024-11-12', approved: true },
        { visitor_name: 'Ravi Kumar', city: 'Bengaluru', rating: 5, review: 'We made a road trip from Bengaluru just for this. The guided tour was fascinating — learning how pepper was once traded for gold, and seeing vanilla orchids in person changed how I see my spice rack.', visit_date: '2024-10-05', approved: true },
        { visitor_name: 'Dr. Meena Patel', city: 'Mumbai', rating: 5, review: 'As an Ayurvedic practitioner, I was blown away by the depth of botanical knowledge the guides possess. Every plant is presented with its Ayurvedic properties and historical context.', visit_date: '2024-09-20', approved: true },
        { visitor_name: 'Arjun Mehta', city: 'Hyderabad', rating: 4, review: 'The photography zone is spectacular during golden hour. Got some of my best macro shots here — pepper vines with dew drops, cardamom pods against green light. Will definitely come back!', visit_date: '2024-11-28', approved: true },
        { visitor_name: 'Lakshmi Venkat', city: 'Chennai', rating: 5, review: 'Our school group of 45 students had an incredible time. The educators tailored the tour beautifully. The spice tasting session was the highlight — students who had never cared about science suddenly wanted to know everything!', visit_date: '2024-10-18', approved: true },
        { visitor_name: 'Rahul Goel', city: 'Delhi', rating: 5, review: 'I thought I knew spices. I was wrong. The star anise session alone taught me three things I\'d never read in any cookbook. The yoga session at sunrise in the spice garden is something I\'ll remember forever.', visit_date: '2024-12-01', approved: true }
    ]).select();

    if (testErr && testErr.code !== '23505') {
        console.error('Testimonial insert error:', testErr.message);
    } else {
        console.log('Testimonials inserted successfully!');
    }

    const { error: galleryErr } = await supabase.from('gallery_images').insert([
        { image_url: 'https://images.unsplash.com/photo-1596040033229-a9821ebd058d?w=800', caption: 'Morning light through cardamom plants', category: 'Spices', sort_order: 1, active: true },
        { image_url: 'https://images.unsplash.com/photo-1588167056547-c3fd72d7a0e5?w=800', caption: 'Black pepper vines in full season', category: 'Spices', sort_order: 2, active: true },
        { image_url: 'https://images.unsplash.com/photo-1615485290382-441e4d049cb5?w=800', caption: 'Fresh turmeric rhizomes at harvest', category: 'Spices', sort_order: 3, active: true },
        { image_url: 'https://images.unsplash.com/photo-1441974231531-c6227db76b6e?w=800', caption: 'Nature walk through botanical trails', category: 'Visitors', sort_order: 4, active: true },
        { image_url: 'https://images.unsplash.com/photo-1506126613408-eca07ce68773?w=800', caption: 'Sunrise yoga in the spice garden', category: 'Events', sort_order: 5, active: true },
        { image_url: 'https://images.unsplash.com/photo-1589927986089-35812388d1f4?w=800', caption: 'Ginger rhizomes ready for harvest', category: 'Spices', sort_order: 6, active: true },
        { image_url: 'https://images.unsplash.com/photo-1471684644823-6f74e5e4e2e6?w=800', caption: 'Photography in the botanical zone', category: 'Visitors', sort_order: 7, active: true },
        { image_url: 'https://images.unsplash.com/photo-1558346490-a72e53ae2d4f?w=800', caption: 'Lemongrass grove in evening light', category: 'Spices', sort_order: 8, active: true },
        { image_url: 'https://images.unsplash.com/photo-1564671165093-20688ff1fffa?w=800', caption: 'Evening view of Indira Park', category: 'Aerial', sort_order: 9, active: true },
        { image_url: 'https://images.unsplash.com/photo-1526318472351-c75fcf070305?w=800', caption: 'Chili plants in full bloom', category: 'Spices', sort_order: 10, active: true }
    ]).select();

    if (galleryErr && galleryErr.code !== '23505') {
        console.error('Gallery insert error:', galleryErr.message);
    } else {
        console.log('Gallery images inserted successfully!');
    }

    const { error: eventsErr } = await supabase.from('events').insert([
        { title: 'Ugadi Spice Harvest Festival', description: 'Join us for our annual Ugadi celebration featuring a traditional spice harvest ritual, fresh-picked cardamom tastings, guided Ayurvedic medicine tours, and a Hyderabadi spice biryani lunch.', event_date: '2026-03-30T08:00:00+05:30', event_type: 'Festival', active: true },
        { title: 'Yoga in the Spice Garden — Spring Sessions', description: 'Morning yoga and pranayama surrounded by aromatic lemongrass and cardamom plants. Sessions led by certified yoga instructor. Limited to 20 participants.', event_date: '2026-04-07T06:30:00+05:30', event_type: 'Wellness', active: true },
        { title: 'Botanical Photography Masterclass', description: 'A hands-on masterclass in botanical macro photography. Learn composition, natural lighting techniques, and how to capture the texture and color of spice plants.', event_date: '2026-04-12T16:30:00+05:30', event_type: 'Workshop', active: true }
    ]).select();

    if (eventsErr && eventsErr.code !== '23505') {
        console.error('Events insert error:', eventsErr.message);
    } else {
        console.log('Events inserted successfully!');
    }

    const { error: blogErr } = await supabase.from('blog_posts').insert([
        { title: 'The Secret Life of Cardamom Pods', slug: 'secret-life-of-cardamom', excerpt: 'Cardamom is the world\'s third most expensive spice by weight, and understanding its harvest cycle reveals why.', content: 'Walking through the cardamom section of Spice Garden at sunrise, when the pods are heavy with morning dew and the air carries their extraordinary fragrance, you understand immediately why this spice was once worth three times its weight in silver.\n\nCardamom (Elettaria cardamomum) grows as a perennial herb in tropical forests, reaching up to 5 meters tall. Each plant produces elongated pods through basal shoots — meaning the pods grow right from the base of the plant, close to the ground, rather than on the leaves or stalks.\n\nAt Spice Garden, we grow three varieties: Alleppey Green (the most prized), Coorg Green, and Mysore. Each has a subtly different flavor profile — Alleppey being more intensely aromatic, Coorg more balanced, and Mysore slightly sweeter.', category: 'Spice Stories', author: 'Spice Garden Team', published: true, published_at: '2024-11-15T09:00:00+05:30', featured_image_url: 'https://images.unsplash.com/photo-1632396870809-bcb65da5f0d9?w=800' },
        { title: 'Why Turmeric Works Best with Black Pepper', slug: 'turmeric-and-black-pepper', excerpt: 'Ancient Ayurvedic wisdom confirmed by modern molecular science — the reason Indians always combined these two spices is biological.', content: 'For thousands of years, Indian cooking and Ayurvedic medicine combined turmeric and black pepper almost instinctively. The Charaka Samhita — a foundational Ayurvedic text — prescribed the combination for treating inflammation.\n\nTurmeric\'s active compound, curcumin, has potent anti-inflammatory and antioxidant properties. But it has one critical weakness: incredibly poor bioavailability. When you consume curcumin alone, your liver metabolizes and excretes it so rapidly that almost none reaches your bloodstream.\n\nBlack pepper\'s piperine changes everything. Studies show piperine increases curcumin bioavailability by 2,000%. This is why haldi doodh (golden milk) has always included black pepper — long before anyone understood the molecular mechanism.', category: 'Ayurveda', author: 'Dr. Ananya Krishnamurthy', published: true, published_at: '2024-10-28T09:00:00+05:30', featured_image_url: 'https://images.unsplash.com/photo-1615485290382-441e4d049cb5?w=800' },
        { title: 'Hyderabad Through the Spice Route', slug: 'hyderabad-spice-route-history', excerpt: 'The story of Hyderabad is inseparable from the history of spices. How the Nizam\'s city became a culinary capital.', content: 'Hyderabad\'s culinary identity — the biryani, the haleem, the rich Mughal-influenced gravies — cannot be understood without understanding the spice trade routes that shaped the city.\n\nThe city was founded in 1591 by Muhammad Quli Qutb Shah, positioned as a crossroads between the northern Mughal empire and the spice-producing south. Caravans carrying cardamom from Kerala and black pepper converged here.\n\nThe Hyderabadi kitchen that emerged from this convergence was extraordinary — taking the Mughal tradition of Persian-influenced biryanis and enriching them with the aromatic intensity of southern spices.', category: 'History', author: 'Spice Garden Team', published: true, published_at: '2024-12-05T09:00:00+05:30', featured_image_url: 'https://images.unsplash.com/photo-1564671165093-20688ff1fffa?w=800' }
    ]).select();

    if (blogErr && blogErr.code !== '23505') {
        console.error('Blog insert error:', blogErr.message);
    } else {
        console.log('Blog posts inserted successfully!');
    }

    console.log('\n✅ Database seeding complete! Restart the backend server.');
}

runSeed().catch(console.error);
